spring:
  application:
    name: billboard-social-service

  config:
    import: "optional:configserver:http://103.95.132.167:8888"

  data:
    redis:
      password: 8tJSGqZ1g9raKtH2g31xqD2rSlFAchRV

  cloud:
    config:
      uri: "http://103.95.132.167:8888"
      username: "${CONFIG_USER_NAME:configuser}"
      password: "${CONFIG_PASSWORD:configpassword}"
      fail-fast: true
      retry:
        initial-interval: 1000
        max-attempts: 6
        max-interval: 2000
        multiplier: 1.1
    bus:
      enabled: true

management:
  health:
    rabbit:
      enabled: false
