spring.application.name=chat_application
server.port=8082
spring.datasource.url=jdbc:postgresql://ep-solitary-math-ah3pwuz0-pooler.c-3.us-east-1.aws.neon.tech:5432/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_JQcrT25lbRht
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA (optional)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=500000ms
# Session TTL Configuration (in seconds)
chat.session.ttl-seconds=30000
